### PR TITLE
docs: apply k8s style guide to HRQ quickstart example

### PR DESCRIPTION
**Pull request by agilgur5**
## Summary

Apply more of [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#content-best-practices) to HRQ quickstart example
- Follow-up to #315 with some style changes

## Details

- consistently use [present tense](https://kubernetes.io/docs/contribute/style/style-guide/#use-present-tense) and [active voice](https://kubernetes.io/docs/contribute/style/style-guide/#use-active-voice)
- consistently [address the reader as "you"](https://kubernetes.io/docs/contribute/style/style-guide/#address-the-reader-as-you)

### CODE REVIEW

**Comment by agilgur5** [comment]
@adrianludwin could you review this docs PR as well?

**Comment by rjbez17** [comment]
Looks like there are some merge conflicts. When you have a few, mind fixing them up and we can get this merged in. Thanks!

**Comment by agilgur5** [comment]
@rjbez17 rebased and fixed all merge conflicts

**Comment by adrianludwin** [comment]
Thanks for this change!

/lgtm

**Pull request merged**
