### PR TITLE
Migrate to Ginkgo V2 #188

### LINKED ISSUE #188: Migrate to Ginkgo V2
According to https://onsi.github.io/ginkgo/MIGRATING_TO_V2
It is advised migration to V2 and this implies some changes in the test files

### PR DESCRIPTION
**Pull request by nobbs**
Migrated by updating ginkgo to v2.1.3 and gomega to v1.19.0. Fixed the few deprecated or updated function calls.

Fixes #188.

Tested: ran both `make test` as well as `make test-e2e`(without repair configured) without any tests failing (against an AKS 1.21.9 cluster)

---

Two notes:

First, the custom reporters of v1 got replaced by a new system (https://onsi.github.io/ginkgo/MIGRATING_TO_V2#improved-reporting-infrastructure). I've simply removed the custom reporter (`printer.NewlineReporter{}`) for now, thus the output format changed a bit. 

Old style of output:
```
$ make test-smoke
go clean --testcache
go test -v -timeout 0 ./test/e2e/... -args --ginkgo.focus "Quickstart"
=== RUN   TestE2e
Running Suite: HNC Suite
========================
Random Seed: 1649356976
Will run 5 of 36 specs

SSSSSSSSSSSSSSSSS
------------------------------
• [SLOW TEST:56.381 seconds]
Quickstart
/home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:11
  Should test basic functionalities in quickstart
  /home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:33
------------------------------
• [SLOW TEST:36.808 seconds]
Quickstart
/home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:11
  Should propagate different types
  /home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:81
------------------------------
• [SLOW TEST:78.279 seconds]
Quickstart
/home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:11
  Should integrate hierarchical network policy
  /home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:105
------------------------------
• [SLOW TEST:71.959 seconds]
Quickstart
/home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:11
  Should create and delete subnamespaces
  /home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:194
------------------------------
• [SLOW TEST:28.294 seconds]
Quickstart
/home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:11
  Should demonstrate exceptions
  /home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:253
------------------------------
SSSSSSSSSSSSSS

Ran 5 of 36 Specs in 271.721 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 31 Skipped

You're using deprecated Ginkgo functionality:
=============================================
Ginkgo 2.0 is under active development and will introduce several new features, improvements, and a small handful of breaking changes.
A release candidate for 2.0 is now available and 2.0 should GA in Fall 2021.  Please give the RC a try and send us feedback!
  - To learn more, view the migration guide at https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md
  - For instructions on using the Release Candidate visit https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta
  - To comment, chime in at https://github.com/onsi/ginkgo/issues/711

  You are using a custom reporter.  Support for custom reporters will likely be removed in V2.  Most users were using them to generate junit or teamcity reports and this functionality will be merged into the core reporter.  In addition, Ginkgo 2.0 will support emitting a JSON-formatted report that users can then manipulate to generate custom reports.

  If this change will be impactful to you please leave a comment on https://github.com/onsi/ginkgo/issues/711
  Learn more at: https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#removed-custom-reporters

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=1.16.5

--- PASS: TestE2e (271.73s)
PASS
ok      sigs.k8s.io/hierarchical-namespaces/test/e2e    271.733s
```

New Style: 
```
$ make test-smoke
go clean --testcache
go test -v -timeout 0 ./test/e2e/... -args --ginkgo.focus "Quickstart"
=== RUN   TestE2e
Running Suite: HNC Suite - /home/nobbs/devel/hierarchical-namespaces/test/e2e
=============================================================================
Random Seed: 1649355271

Will run 5 of 36 specs
SSSSSSSSSSSS
------------------------------
P [PENDING]
Issues Should have CannotPropagateObject and CannotUpdateObject events - replacing obsolete issues #328, #605, #771
/home/nobbs/devel/hierarchical-namespaces/test/e2e/issues_test.go:221
------------------------------
SSSSSSSSSSSSSSSSSS
------------------------------
• [SLOW TEST] [37.767 seconds]
Quickstart Should test basic functionalities in quickstart
/home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:33
------------------------------
• [SLOW TEST] [37.489 seconds]
Quickstart Should propagate different types
/home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:81
------------------------------
• [SLOW TEST] [91.509 seconds]
Quickstart Should integrate hierarchical network policy
/home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:105
------------------------------
• [SLOW TEST] [67.307 seconds]
Quickstart Should create and delete subnamespaces
/home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:194
------------------------------
• [SLOW TEST] [29.315 seconds]
Quickstart Should demonstrate exceptions
/home/nobbs/devel/hierarchical-namespaces/test/e2e/quickstart_test.go:253
------------------------------

Ran 5 of 36 Specs in 263.389 seconds
SUCCESS! -- 5 Passed | 0 Failed | 1 Pending | 30 Skipped
--- PASS: TestE2e (263.39s)
PASS
ok      sigs.k8s.io/hierarchical-namespaces/test/e2e    263.399s
```

Changes are minimal, less newlines. If the other systems like the automated (?) builds are not dependent on the format of output, this is probably no issue.

Second, the `BeforeSuite` signature changed, there's no `timeout` argument anymore. Again, I've simply removed that, as I couldn't figure out how to best replicate the timeout in the new version.

### CODE REVIEW

**Comment by erikgb** [comment]
Thanks for this @nobbs!

/ok-to-test

**Comment by erikgb** [comment]
@nobbs Could you update the description to auto-close #188 on merge, please?

**Comment by nobbs** [comment]
> @nobbs Could you update the description to auto-close #188 on merge, please?

Done. And accidentally dropped your lgtm-label, sorry ;)

**Comment by adrianludwin** [comment]
The text "Fixes #188" can't be in the _commit_ message, can you please take that out and re-push? It can be in the _PR_ description though (which is already is). Afterwards I can approve it, thanks!

**Comment by nobbs** [comment]
Alright, got it now. Sorry and thanks for the help!

**Comment by adrianludwin** [comment]
Thanks for this!
/lgtm
/approve

**Pull request merged**
