### PR TITLE
Add security context

### LINKED ISSUE #181: Security Context
Successfuly tested restricted namespace enforcing v1.23 and pod security standards

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/enforce: restricted  
    pod-security.kubernetes.io/enforce-version: v1.23
  name: hnc-system

```

Also security context for controller-manager

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: hnc-controller-manager
  namespace: hnc-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --webhook-server-port=9443
        - --metrics-addr=:8080
        - --max-reconciles=10
        - --apiserver-qps-throttle=50
        - --excluded-namespace=kube-system
        - --excluded-namespace=kube-public
        - --excluded-namespace=hnc-system
        - --excluded-namespace=kube-node-lease
        - --excluded-namespace=openebs
        - --excluded-namespace=default
        - --excluded-namespace=gitlab-kubernetes-agent
        - --excluded-namespace=cilium-monitoring
        - --enable-internal-cert-management
        - --cert-restart-on-secret-refresh
        command:
        - /manager
        image: gcr.io/k8s-staging-multitenancy/hnc-manager:v1.0.0
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: 8081
          periodSeconds: 10
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
...
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]

...
...

```

### PR DESCRIPTION
**Pull request by rgherta**
Fixes #181
Tested: test-smoke, test-e2e

```
go clean --testcache
go test -v -timeout 0 ./test/e2e/... -args --ginkgo.focus "Quickstart"
=== RUN   TestE2e
Running Suite: HNC Suite
========================
Random Seed: 1650309465
Will run 5 of 36 specs

SSSSSSSSSSSSSSSSSS
------------------------------
• [SLOW TEST:30.375 seconds]
Quickstart
/home/romang/Documents/hierarchical-namespaces/test/e2e/quickstart_test.go:11
  Should test basic functionalities in quickstart
  /home/romang/Documents/hierarchical-namespaces/test/e2e/quickstart_test.go:33
------------------------------
• [SLOW TEST:30.292 seconds]
Quickstart
/home/romang/Documents/hierarchical-namespaces/test/e2e/quickstart_test.go:11
  Should propagate different types
  /home/romang/Documents/hierarchical-namespaces/test/e2e/quickstart_test.go:81
------------------------------

S [SKIPPING] [67.745 seconds]
Quickstart
/home/romang/Documents/hierarchical-namespaces/test/e2e/quickstart_test.go:11
  Should integrate hierarchical network policy [It]
  /home/romang/Documents/hierarchical-namespaces/test/e2e/quickstart_test.go:105

  Basic network policies don't appear to be working; skipping the netpol quickstart

  /home/romang/Documents/hierarchical-namespaces/test/e2e/quickstart_test.go:165
------------------------------
• [SLOW TEST:62.344 seconds]
Quickstart
/home/romang/Documents/hierarchical-namespaces/test/e2e/quickstart_test.go:11
  Should create and delete subnamespaces
  /home/romang/Documents/hierarchical-namespaces/test/e2e/quickstart_test.go:194
------------------------------


• [SLOW TEST:22.588 seconds]
Quickstart
/home/romang/Documents/hierarchical-namespaces/test/e2e/quickstart_test.go:11
  Should demonstrate exceptions
  /home/romang/Documents/hierarchical-namespaces/test/e2e/quickstart_test.go:253
------------------------------
SSSSSSSSSSSSS

Ran 4 of 36 Specs in 213.345 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 32 Skipped
```

### CODE REVIEW

**Comment by tashimi** [comment]
ping @adrianludwin @rjbez17 

/unassign @tashimi

**Comment by adrianludwin** [comment]
Hey @rgherta , thanks for this! Before I approve, can you please make a few changes?

* The tests you ran didn't exercise your changes - the `test/e2e` would have tested them, but they take about 15-30m to run. To run those tests, point your `kubectl` at a cluster, run `make deploy` to deploy HNC onto that cluster, then run `make test-smoke` (this runs a subset of the e2e tests and should only take about 5min). Can you please run those?
* Can you please give the commit a more descriptive name? E.g. "Add pod security contexts" or whatever the correct name of this feature is. Please also include the details about why you're making this change, any other details that might be useful, plus what testing you did in the _commit_, not the PR description. A good example is https://github.com/kubernetes-sigs/hierarchical-namespaces/commit/75a2052036d7240534f090c40217c42bff24cf0c.
  * For this change, the "Tested:" paragraph might just be `Tested: make smoke-test passes`

Thanks!

**Comment by adrianludwin** [comment]
BTW you can update the commit message just by `git commit --amend` and then force-push it to your branch, probably something like `git push origin -f`, you don't need to close this PR and file a new one.

**Comment by rgherta** [comment]
> Hey @rgherta , do you need a hand on this? Is everything clear?

all clear, sorry for thr delay

**Comment by adrianludwin** [comment]
No worries! LMK if you have any questions about running the tests.

**Comment by adrianludwin** [comment]
lgtm but I wouldn't mind if Ryan could have look as well. Thanks for making this change!

/approve
/lgtm
/hold
/assign @rjbez17

**Pull request merged**
