### PR TITLE
Fix probes when installing on a fresh cluster

### LINKED ISSUE #158: Getting error "tls.crt: no such file or directory" when building HNC from main branch
Hi,

Environment details:
Rancher: 2.6.2
k8s cluster: EKS
k8s version: v1.21.5

We tried to generate manifests and image by building source from main branch. We were able to do that. However , when we deploy the manifests, we were getting error 
```
"msg":"problem running manager","error":"open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory","stacktrace":"runtime.main\n\t/usr/local/go/src/runtime/proc.go:255" 
```
The similar issue was mentioned https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/139#issuecomment-1036615144.

We would like to use HNC feature of label and annotation propagation and require to fix above error. It would be great if you could elaborate to set up the certificates using cert manager. We do have cert manager installed in our environment.

Thanks in advance.

### PR DESCRIPTION
**Pull request by adrianludwin**
Fixes #158

If the Secret with the certs doesn't exist, starting the
webhook server will fail and HNC will exit. Before we configured the
probes, we carefully didn't start the webhook server until after the
certs were ready, but as a side effect of creating the probe functions,
we accidentally started the webhook server before the certs were
generated. This worked fine on a cluster that already had the certs
(like the one I was testing on) but failed for everyone else (oops).

The fix is simply to use a non-default checker that knows whether the
certs have been generated, and avoids accidentally starting the webhook
server if the certs don't exist yet.

Tested: manually on a cluster without the Secret. Without this change, I
can see the error from the webhook server complaining that the certs
don't exist; with this change, I can see that that in HNC's first
invocation, we get some "healthz check failed" messages, but the cert
controller runs, generates the certs, and restarts HNC. The second
invocation works just fine.

### CODE REVIEW

**Comment by erikgb** [comment]
While this solution seems ok, I think the canonical solution would be to start with a dummy certificate that later will be replaced by the certificate-provider. Just to solve the bootstrapping problem. That is how I would solve this using cert-manager. But I also think certificates should be provided **to** the application, and _not provided by_ the application.

/lgtm

**Comment by erikgb** [comment]
Oooops, I didn't think my lgtm would merge this. Sorry! I should have added a hold to get some discussions around my comment.

**Comment by rjbez17** [comment]
I wonder if it may be worthwhile to reconsider removing the cert creation logic altogether from startup? Just have a dependency that certs are provided. We take in a secret and k8s will prevent us from starting until the secret exists. Then we can have a separate (optional) startup job that does any and all cert creation logic or leave it to users to not run the job if they have their own solution (cert manager). I know we discussed this in the past but I don't remember why we didn't like that approach? To handle cert rotations the job could be a cron job for self signed and cert manager handles for others. We just need a watcher on the mounted secret file to reload HNC on change.

This would guarantee we have a cert at startup.

**Comment by adrianludwin** [comment]
I really like having a one-step install to make it easy to try out, not to
mention write tests for or even just test manually on a new cluster. Plus
cert-controller already existed so we didn't need to write anything
ourselves.

I'd rather go with the approach in #159 where we simply build multiple
manifests to make it easy for cert-manager users as well. wdyt?

**Comment by erikgb** [comment]
I agree with @rjbez17. The current approach will complicate the code more over time, and put HNC further away from controller-runtime and kubebuilder. I'll vote for cert-manager as the default - as suggested by kubebuilder in the skaffolding process. And eventually an opt-in for cert-rotator, that could be used in tests - with some test adjustments. Or just use a self-signed cert in the tests and drop the cert-rotator.

**Comment by adrianludwin** [comment]
We did start with cert-manager as the default (and only) method but it made
development and experimentation difficult.

Can you or Ryan maybe create a setup script to show what a standalone
installer would look like, without either cert-controller or cert-manager?

**Pull request merged**
