### PR TITLE
change resource quota name #275

### PR DESCRIPTION
**Pull request by keisukesakasai**
### What this PR does it:
I have renamed the name of the Resource Quotas created from HRQ.
Originally, the name of the ResourceQuotas was ```hrq.hnc.x-k8s.io```, but it has been changed to ```local-impl.hnc.x-k8s.io``` as part of this update. 
Please refer to this link: https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/275#issuecomment-1564981395.

### Operation confirmation:
I have confirmed that the name of the Resource Quota created from HRQ is ```local-impl-hrq.hnc.x-k8s.io```.

The confirmation steps are as follows.

- Create parent-child relationships between namespaces as usual.
- Create HRQ.
- Confirm the names of ResourceQuotas created from HRQ for each namespace.

ns relationship:
```console
❯ k hns tree parent
parent
└── [s] child
```

create HRQ:
```console
❯ kubectl apply -f - << EOF
apiVersion: hnc.x-k8s.io/v1alpha2
kind: HierarchicalResourceQuota
metadata:
  name: parent-hrq
  namespace: parent
spec:
  hard:
    limits.memory: 500Mi
    requests.memory: 500Mi
    limits.cpu: "2"
    requests.cpu: "2"
EOF
hierarchicalresourcequota.hnc.x-k8s.io/parent-hrq created

❯ k get hrq -nparent
NAME         REQUEST                                       LIMIT
parent-hrq   requests.cpu: 0/2, requests.memory: 0/500Mi   limits.cpu: 0/2, limits.memory: 0/500Mi
```

Check the names of the ResourceQuotas created from HRQ:
```console
❯ k get resourcequotas -nparent
NAME                          AGE   REQUEST                                       LIMIT
local-impl-hrq.hnc.x-k8s.io   54s   requests.cpu: 0/2, requests.memory: 0/500Mi   limits.cpu: 0/2, limits.memory: 0/500Mi

❯ k get resourcequotas -nchild
NAME                          AGE    REQUEST                                       LIMIT
local-impl-hrq.hnc.x-k8s.io   115s   requests.cpu: 0/2, requests.memory: 0/500Mi   limits.cpu: 0/2, limits.memory: 0/500Mi
```

### Tested:
Unit and E2E tests has passed.

### Which issue(s) this PR fixes:
https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/275

### CODE REVIEW

**Comment by keisukesakasai** [comment]
@adrianludwin  please take a look? thx!

**Comment by adrianludwin** [comment]
I'm out this week, will look when I'm back next week, sorry!

**Comment by adrianludwin** [comment]
Sorry for disappearing again...

I'm having second thoughts about this - firstly (and most importantly), this doesn't clean up any existing `hrq` resource quotas, so this will leave a bunch of stranded RQs around. We could fix that, but I'm not sure it's worth the trouble? Especially now that #283 has been merged.

If anything, perhaps we could add some kind of annotation with a human-readable message basically saying "don't read this."

**Comment by mochizuki875** [comment]
@adrianludwin 
> this doesn't clean up any existing hrq resource quotas, so this will leave a bunch of stranded RQs around. 

As you said, compatibility is important and this may cause breaking changes.
So I agree with your idea.(leaving it alone)

And I think we should add some annotations to HRQ document.
For example, add here with clarifying the RQ name `hrq.hnc.x-k8s.io`:

https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/74fe01460083fd410a8fbd728eb255c4d728dbcb/docs/user-guide/concepts.md?plain=1#L284-L286

https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/74fe01460083fd410a8fbd728eb255c4d728dbcb/docs/user-guide/quickstart.md?plain=1#L517

@keisukesakasai 
What do you think?

**Comment by adrianludwin** [comment]
Hey @mochizuki875 that sounds like a good idea, thanks!

**Comment by rjbez17** [comment]
@mochizuki875 are we abandoning this?

**Comment by mochizuki875** [comment]
@rjbez17 
Yes, so we should close this PR.
/close

**Pull request closed without merging**
