### PR TITLE
Add `staticcheck` to the make build process

### PR DESCRIPTION
**Pull request by nobbs**
Since most of @erikgb's refactoring PRs have been merged by now, this PR adds `staticcheck` to the Makefile and fixes the last warnings. This basically implements #146.

I haven't done any major changes to the code - unused functions are still in place and simply ignored; if you're sure that they won't be needed anymore, I'll gladly remove them.

---

Add `staticcheck` to the build process, including a `check-tools` make task that installs `staticcheck` if necessary. `staticcheck` is a golang linter / static analysis tool that raises warnings and errors if it finds any problems in the codebase. The `staticcheck` step is also run during various `make` tasks (e.g. `build`) and **blocks the build if any _errors or warnings_** are encountered.

Tested: `make test` was run successfully.

### CODE REVIEW

**Comment by adrianludwin** [comment]
Is this urgent for v1.0? I'd rather delay this to v1.1 at this point.

**Comment by adrianludwin** [comment]
sgtm, thanks

**Comment by erikgb** [comment]
I think unused code should be removed, but is also ok with leaving it there for now - if anyone thinks it can come to use in the future. Thanks for fixing this @nobbs!

**Review by adrianludwin — COMMENTED** [review]
Thanks for this change!

/lgtm
/approve

**Pull request merged**
