### PR TITLE
cherry pick of #283: Show HierarchicalResourceQuota status by kubectl-hns

### PR DESCRIPTION
**Pull request by keisukesakasai**
Cherry pick of https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/283 on master.

https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/283: Show HierarchicalResourceQuota status by kubectl-hns

The discussion regarding the content can be found here:
https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/274#issuecomment-1564928132

### CODE REVIEW

**Comment by rjbez17** [comment]
/ok-to-test 
/lgtm

@adrianludwin I'll let you approve since you requested the cherry pick

**Comment by mochizuki875** [comment]
Patch PR #286 is in the works, so please wait for the merge.
I think we should cherry-pick #286 instead of #283.

**Comment by adrianludwin** [comment]
Ok @mochizuki875 thanks for catching that. I'll leave this on hold.

**Comment by keisukesakasai** [comment]
I created a new pull request, so I will close this one. https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/290

**Pull request closed without merging**
