### PR TITLE
Apple M1 support

### PR DESCRIPTION
**Pull request by simonoff**
Its adding support for Apple M1 in build scripts. Could be that I missed something like a docker build or something like this.

### CODE REVIEW

**Comment by rjbez17** [comment]
/ok-to-test

Thanks for this @simonoff! Can you please sign the CLA so we can get this merged in?

**Comment by simonoff** [comment]
@rjbez17 I have signed it already.

**Comment by rjbez17** [comment]
@simonoff  we are in a transition period moving away from the Linux Foundation CLA -> Easy CLA. However, Easy CLA isn't fully rolled out yet (and wont for a bit yet). If you wouldn't mind signing the linux foundation CLA, it would speed things up. 

You can follow along with the EasyCLA rollout here: https://github.com/kubernetes/org/issues/3068

**Comment by simonoff** [comment]
hm... i have changed and an email and other things. But still not accepted by CLA.

**Comment by rjbez17** [comment]
Does the email in your git commit match what you signed the CLA with?

**Comment by simonoff** [comment]
@rjbez17 yes, i have made a force commit. and github user name and email were added there.

**Comment by adrianludwin** [comment]
Sorry just looking into this now.

I think you may need to add a `Signed-off-by: Name <email>` to the commit message. E.g. see https://github.com/kubernetes-sigs/hierarchical-namespaces/commit/04df75b9d27143a48545f7fa9da3bb7cfd8992d9. See if that works?

**Comment by adrianludwin** [comment]
Fixes #113

**Comment by rjbez17** [comment]
EasyCLA went live over the weekend. Lets hope a retest fixes this.

**Comment by adrianludwin** [comment]
Cool thanks!

**Pull request merged**
